#!/bin/bash

ROOT=$(cd $(dirname "$0") && pwd)
cd ${ROOT} || exit 1

for DEMO in ${ROOT}/*/; do
  [ -d "${DEMO}" ] || continue

  [ -x "${DEMO}/Setup" ] || continue

  (
    cd "${DEMO}" &&
    timeout --kill-after=60 45 ./Setup
  )
done

